// Generated by lsc from scoring.ts

function MathMax(a: int, b: int): int { if a >= b then a else b }

function MaxOfSeq(s: seq<int>): int
  requires |s| > 0
  ensures forall i: nat :: i < |s| ==> s[i] <= MaxOfSeq(s)
  ensures exists i: nat :: i < |s| && s[i] == MaxOfSeq(s)
  decreases |s|
{
  if |s| == 1 then s[0]
  else MathMax(s[0], MaxOfSeq(s[1..]))
}

// Helper for proofs about MaxOfSeq applied to concatenations. Users invoke
// this in _ensures lemma bodies when Dafny doesn't automatically connect
// indices through (a + b)[i].
lemma MaxOfSeqConcat(a: seq<int>, b: seq<int>)
  requires |a| + |b| > 0
  ensures forall i: nat :: i < |a| ==> a[i] <= MaxOfSeq(a + b)
  ensures forall i: nat :: i < |b| ==> b[i] <= MaxOfSeq(a + b)
{
  forall i: nat | i < |a| ensures a[i] <= MaxOfSeq(a + b) {
    assert (a + b)[i] == a[i];
  }
  forall i: nat | i < |b| ensures b[i] <= MaxOfSeq(a + b) {
    assert (a + b)[|a| + i] == b[i];
  }
}

datatype OptionVotes = OptionVotes(id: string, yes: int, ifNeedBe: int)

datatype ScoredOption = ScoredOption(id: string, yes: int, ifNeedBe: int, score: int, isTopChoice: bool)

datatype PollScoring = PollScoring(options: seq<ScoredOption>, highScore: int)

method scorePoll(input: seq<OptionVotes>) returns (res: PollScoring)
  requires forall i: nat :: ((i < |input|) ==> ((input[i].yes >= 0) && (input[i].ifNeedBe >= 0)))
  requires forall i: nat :: ((i < |input|) ==> (input[i].yes < 1000))
  ensures (|res.options| == |input|)
  ensures (res.highScore >= 0)
  ensures forall i: nat :: ((i < |res.options|) ==> (res.options[i].score >= 0))
  ensures forall i: nat :: ((i < |res.options|) ==> (res.options[i].score <= res.highScore))
  ensures forall i: nat :: ((i < |res.options|) ==> (res.options[i].isTopChoice == ((res.options[i].score == res.highScore) && (res.options[i].score > 0))))
  ensures forall i: nat :: ((i < |res.options|) ==> (res.options[i].score == (((input[i].yes + input[i].ifNeedBe) * 1000) + input[i].yes)))
  ensures forall i: nat, j: nat :: ((i < |res.options|) ==> (j < |res.options|) ==> (input[i].yes >= input[j].yes) ==> (input[i].ifNeedBe >= input[j].ifNeedBe) ==> (res.options[i].score >= res.options[j].score))
  ensures forall i: nat, j: nat :: ((i < |res.options|) ==> (j < |res.options|) ==> (res.options[i].score == res.options[j].score) ==> ((input[i].yes == input[j].yes) && (input[i].ifNeedBe == input[j].ifNeedBe)))
{
  var scores := seq(|input|, i_map requires 0 <= i_map < |input| => var o := input[i_map]; (((o.yes + o.ifNeedBe) * 1000) + o.yes));
  var i_t0 := MaxOfSeq((scores + [0]));
  var highScore := i_t0;
  var options: seq<ScoredOption> := [];
  var i := 0;
  while (i < |input|)
    invariant (0 <= i)
    invariant (i <= |input|)
    invariant (|options| == i)
    invariant forall j: nat :: ((j < i) ==> (options[j].score == scores[j]))
    invariant forall j: nat :: ((j < i) ==> (options[j].score >= 0))
    invariant forall j: nat :: ((j < i) ==> (options[j].score <= highScore))
    invariant forall j: nat :: ((j < i) ==> (options[j].isTopChoice == ((options[j].score == highScore) && (options[j].score > 0))))
  {
    var o := input[i];
    var score := scores[i];
    options := (options + [ScoredOption(o.id, o.yes, o.ifNeedBe, score, ((score == highScore) && (score > 0)))]);
    i := (i + 1);
  }
  return PollScoring(options, highScore);
}
