// Generated by lsc from redirect.ts

datatype Option<T> = None | Some(value: T)

predicate IsJSWhitespace(c: char)
{
  c == '\U{0009}' || c == '\U{000A}' || c == '\U{000B}' || c == '\U{000C}' || c == '\U{000D}' ||
  c == '\U{0020}' || c == '\U{00A0}' || c == '\U{1680}' ||
  ('\U{2000}' <= c <= '\U{200A}') ||
  c == '\U{2028}' || c == '\U{2029}' || c == '\U{202F}' || c == '\U{205F}' ||
  c == '\U{3000}' || c == '\U{FEFF}'
}

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && !IsJSWhitespace(StringTrimLeft(s)[0]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[0]) then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  ensures StringTrimRight(s) == "" || (|StringTrimRight(s)| > 0 && !IsJSWhitespace(StringTrimRight(s)[|StringTrimRight(s)|-1]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[|s|-1]) then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

function validateRedirectUrl(redirectTo: Option<string>): Option<string>
{
  match redirectTo {
    case Some(i_redirectTo_val) =>
      if (|i_redirectTo_val| > 0) then
        var trimmed := StringTrim(i_redirectTo_val);
        if ((|trimmed| >= |"/"| && trimmed[..|"/"|] == "/") && !((|trimmed| >= |"//"| && trimmed[..|"//"|] == "//"))) then
          Some(trimmed)
        else
          None
      else
        None
    case None =>
      None
  }
}

lemma validateRedirectUrl_ensures(redirectTo: Option<string>)
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => (|i_result_val| >= |"/"| && i_result_val[..|"/"|] == "/") case None => true })
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => !((|i_result_val| >= |"//"| && i_result_val[..|"//"|] == "//")) case None => true })
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => (|i_result_val| >= 1) case None => true })
{
}
