// Generated by lsc from redirect.ts

datatype Option<T> = None | Some(value: T)

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && StringTrimLeft(s)[0] != ' ')
  decreases |s|
{
  if |s| == 0 then ""
  else if s[0] == ' ' then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  decreases |s|
{
  if |s| == 0 then ""
  else if s[|s|-1] == ' ' then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

function validateRedirectUrl(redirectTo: Option<string>): Option<string>
{
  match redirectTo {
    case Some(i_redirectTo_val) =>
      if (|i_redirectTo_val| > 0) then
        var trimmed := StringTrim(i_redirectTo_val);
        if ((|trimmed| >= |"/"| && trimmed[..|"/"|] == "/") && !((|trimmed| >= |"//"| && trimmed[..|"//"|] == "//"))) then
          Some(trimmed)
        else
          None
      else
        None
    case None =>
      None
  }
}

lemma validateRedirectUrl_ensures(redirectTo: Option<string>)
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => (|i_result_val| >= |"/"| && i_result_val[..|"/"|] == "/") case None => true })
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => !((|i_result_val| >= |"//"| && i_result_val[..|"//"|] == "//")) case None => true })
  ensures (match validateRedirectUrl(redirectTo) { case Some(i_result_val) => (|i_result_val| >= 1) case None => true })
{
}
